server:
  port: 7000

spring:
  application:
    name: DEPARTMENT-SERVICE

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-fegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
